name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    env:
      POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
      POSTGRES_USER: ${{ secrets.PGUSER_TEST }}
      POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGUSER: ${{ secrets.PGUSER_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
